// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDl8dSsOBEzg9f0HAtAeX6bgtCxI_2m7KQ',
    appId: '1:439285294613:web:f10a5eac76ff9a4083901c',
    messagingSenderId: '439285294613',
    projectId: 'parking-slot-booking-cffbc',
    authDomain: 'parking-slot-booking-cffbc.firebaseapp.com',
    storageBucket: 'parking-slot-booking-cffbc.firebasestorage.app',
    measurementId: 'G-FN10P1TGLJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA1y2kDSVOSTzEI1La_bwUk_M1eAhz5d_0',
    appId: '1:439285294613:android:4eac3441ab23fb2c83901c',
    messagingSenderId: '439285294613',
    projectId: 'parking-slot-booking-cffbc',
    storageBucket: 'parking-slot-booking-cffbc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAQQCNuJYtBf9JcXrByKbgGA1Tyu134Mrw',
    appId: '1:439285294613:ios:4e41e7f9bb25793283901c',
    messagingSenderId: '439285294613',
    projectId: 'parking-slot-booking-cffbc',
    storageBucket: 'parking-slot-booking-cffbc.firebasestorage.app',
    iosBundleId: 'com.example.parkingBooking',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAQQCNuJYtBf9JcXrByKbgGA1Tyu134Mrw',
    appId: '1:439285294613:ios:4e41e7f9bb25793283901c',
    messagingSenderId: '439285294613',
    projectId: 'parking-slot-booking-cffbc',
    storageBucket: 'parking-slot-booking-cffbc.firebasestorage.app',
    iosBundleId: 'com.example.parkingBooking',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDl8dSsOBEzg9f0HAtAeX6bgtCxI_2m7KQ',
    appId: '1:439285294613:web:283d2f0d1d677d4483901c',
    messagingSenderId: '439285294613',
    projectId: 'parking-slot-booking-cffbc',
    authDomain: 'parking-slot-booking-cffbc.firebaseapp.com',
    storageBucket: 'parking-slot-booking-cffbc.firebasestorage.app',
    measurementId: 'G-J4B1QLJKPQ',
  );

}